version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    networks:
      - back-tier
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - /data/mongo/db:/data/db
      - /data/mongo/log:/var/log/mongodb  
    networks:
      - back-tier
networks:
  back-tier:
